# Закріплюємо матеріал.

**До яких типів задач відносяться задачі нижче?** (Class, Regr, Clust)

1. Задача полягає в тому, щоб визначити квіти ірису на три різні види (наприклад, Setosa, Versicolor, Virginica) на основі їхніх вимірів довжини та ширини чашечки та пелюстки.

2. Задача полягає в визначенні електронних листів на дві категорії: спам та не спам, використовуючи характеристики листа, такі як ключові слова, довжина тексту, наявність або відсутність вкладень тощо.

3.  Задача полягає в прогнозуванні вартості будинків на основі різних характеристик, таких як площа, кількість спалень та ванних кімнат, розташування тощо.

4.  Задача полягає в групуванні покупців на основі їхніх покупок, щоб виявити подібні патерни купівельного поведінки та визначити цільові аудиторії.

5. Задача полягає в групуванні новинних статей на основі їхньої тематики або ключових слів, щоб виявити подібність та відмінності між ними.

6. Задача полягає в прогнозуванні кількості електроенергії, яку буде вироблено на певний часовий період, на основі попередніх вимірів, таких як температура, вологість, часові показники тощо.

7. Задача полягає в прогнозуванні оцінок студентів на основі їхньої участі в класах, рівня складності завдань, часу, витраченого на вивчення матеріалу тощо.
8. Задача полягає в групуванні користувачів веб-сайту на основі їхньої активності, такої як перегляди сторінок, час витрачений на сайті, взаємодія з різними елементами тощо.
9. Задача полягає в визначенні пацієнтів на дві категорії: хворі на діабет та здорові, на основі клінічних показників, таких як рівень глюкози в крові, артеріальний тиск, вага тощо.
10. Задача полягає в визначенні текстових документів на основі їхнього змісту, щоб визначити, до якої категорії вони належать (наприклад, наука, спорт, політика тощо).

### Відповіді

1. Class (Класифікація квітів ірису)
2. Class (Визначення електронної пошти як спаму або не спаму)
3. Regr (Прогнозування ціни будинків)
4. Clust (Кластеризація покупців у роздрібних магазинах)
5. Clust (Кластеризація новинних статей)
6. Regr (Прогнозування виробництва електроенергії)
7. Regr (Прогнозування оцінки студентів)
8. Clust (Кластеризація даних про відвідування веб-сайту)
9. Class (Визначення діабету)
10. Class (Визначення теми текстового документа)

# Елементи лінійної алгебри

## Організаційні моменти

Візуалізація векторів і геометричних об'єктів можно робити за допомогою

https://www.math10.com/en/geometry/geogebra/fullscreen.html

В пайтоні всі розрахунки робляться за допомогою бібліотеки numpy, scipy

**NumPy** - це бібліотека для мови програмування Python, яка надає підтримку для роботи з масивами та матрицями, а також для виконання математичних операцій на них. NumPy є скороченням від "Numerical Python". Частини коду можуть бути написані на мові C або Fortran для оптимізації та для виконання чисельних операцій.

https://numpy.org/

In [32]:
!python --version # Версія пайтона в середовищі колаба

Python 3.10.12


In [33]:
import numpy as np
np.__version__ # Версія numpy в середовищі колаба

'1.25.2'

In [ ]:
# Щоб завантажити коректну версію numpy використайте цю команду у вашому середовищі
# pip install numpy==1.25.2

**SciPy** - це високорівнева наукова бібліотека для мови програмування Python, яка розширює можливості NumPy, додаючи функції для роботи з чисельними методами, оптимізацією, інтегруванням, а також іншими математичними алгоритмами та інструментами для наукових обчислень.

https://scipy.org/

In [34]:
import scipy
scipy.__version__

'1.11.4'

In [ ]:
# Щоб завантажити коректну версію scipy використайте цю команду у вашому середовищі
# pip install scipy==1.11.4

### Чому залежності дуже важливі і треба слідкувати уважно за всіма імпортами?

Як порахувати корень із числа за допомгою коду?

In [35]:
# Var 1
from numpy import sqrt
a = 9
print(sqrt(a))

# Var 2
from math import sqrt
a = 9
print(sqrt(a))

3.0
3.0


In [36]:
# Але є нюанс. Який буде результат?
b = [4, 9, 16]
print(sqrt(b))

TypeError: must be real number, not list

In [37]:
from numpy import sqrt as nsqrt
print(nsqrt(b))

[2. 3. 4.]


## Що таке лінійна алгебра (ЛА)? Основні поняття.

**Лінійна алгебра** - це галузь математики, яка вивчає об'єкти та їх взаємодію в лінійних просторах. Основні об'єкти дослідження включають вектори, лінійні підпростори, лінійні перетворення та системи лінійних рівнянь.

Основні поняття ЛА:
- Вектори
- Лінійні простори
- Лінійні перетворення
- Системи лінійних рівнянь (СЛА)

![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Venn_Diagram_of_Numbers.svg/languk-300px-Venn_Diagram_of_Numbers.svg.png)

**Лінійний простір** - це математична структура, що складається з множини елементів, над якою визначено дві операції:
- додавання
- множення на скаляр

Які тоді бувають простори чисел (множин)?
- Натуральні ℕ : {1, 2, 3, 4, 5, ...}
- Цілі ℤ : {..., -3,-2,-1, 0, ℕ} (int)
- Раціональні ℚ: {ℤ , -1.5, - 0.25, 0,01, 20.25, ...}
- Дійсні ℝ: {ℚ, π, e, $\sqrt2$, ...} (float)
- Комплексні ℂ: { ℝ+*i* } (complex)

Властивості дійсних чисел:

https://ukrayinska.libretexts.org/Математика/До_алгебри/Книга%3A_Преалгебра_(OpenStax)/07%3A_Властивості_дійсних_чисел

Дійсні числа

https://uk.wikipedia.org/wiki/Дійсне_число

## Вектора і скаляри

**Вектор** - це об'єкт, який має величину (або довжину) та напрямок. У багатьох випадках вектори визначаються як упорядковані набори чисел, які представляють різницю між двома точками у просторі. Наприклад, у двовимірному просторі вектор може бути представлений як пара чисел (x, y), де x - це компонента по осі X, а y - по осі Y.

**Скаляр** - це число у просторі яке не має напряму та геометричного положення у просторі.

Характеристики вектора
1. Координати початку та кінця вектора

A = $(x_A; y_A)$

B = $(x_B; y_B)$
2. Напрямок

3. Координати вектора -- це довжини кожної з проекцій вектора.

$\vec{AB} = \vec{v}= (x_{AB}; y_{AB}) = (x_B-x_A ; y_B-y_A) $

4. Довжина

$|\vec{AB}| = \sqrt{x_{AB}^2 + y_{AB}^2} $


5. Кут відносно вісій координат

$cos(α) = x_{AB} / |\vec{v}|$

$cos(β) = y_{AB} / |\vec{v}|$





![alt text](https://cdn.economy-pedia.com/8510349/mdulo_de_un_vector_-_qu_es-_definicin_y_concepto_2021_economy-wikicom_2.png.webp)

Реалізація за допомогою numpy

In [38]:
import numpy as np

a = np.array([1,2,3,4,5]) # Викликаємо об'єкт np.array
print(a)
# https://numpy.org/doc/stable/reference/generated/numpy.array.html

[1 2 3 4 5]


In [39]:
import numpy as np
a = np.array(
    [[1,2,3],[4,5,6]], dtype = float)
print(f'Array:\n {a}')
print(f'Shape: {a.shape}')
print(f'Number of dimensions: {a.ndim}') #a.ndim = len(a.shape)
print(f'Size (count of elements): {a.size}')
print(f'Data type of elements in array: {a.dtype}') # https://numpy.org/doc/stable/user/basics.types.html
print(f'Byte size of elements: {a.itemsize}')
print(type(a))

Array:
 [[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3)
Number of dimensions: 2
Size (count of elements): 6
Data type of elements in array: float64
Byte size of elements: 8
<class 'numpy.ndarray'>


In [40]:
# Слайсування
import numpy as np
a = np.array([1,2,3,4,5])
print('Перший елемент\n', a[0])
print('-'*50)
print('Все від другого елементу\n', a[1:])
print('-'*50)
print('Всі елементи до третьйого\n', a[:2])
print('-'*50)
print('Всі елементи через 1\n', a[::2])
print('-'*50)

Перший елемент
 1
--------------------------------------------------
Все від другого елементу
 [2 3 4 5]
--------------------------------------------------
Всі елементи до третьйого
 [1 2]
--------------------------------------------------
Всі елементи через 1
 [1 3 5]
--------------------------------------------------


In [43]:
# Кастомне(униіверсальне) створення векторів за допомогою ndarray
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
import numpy as np

np.ndarray(shape = (2,3),
           buffer = np.array([1,2,3,4,5,6]),
           dtype = 'int64',
           order = 'C'
           )

array([[1, 2, 3],
       [4, 5, 6]])

## Види векторів

**Нульовим вектором** -  називають вектор, у якого початок і кінець збігаються, позначення $\vec 0$ або просто 0.

$\vec 0 = (0; 0)$

**Одиничним вектором** називається вектор, довжина якого дорівнює одиниці.

$|\vec I| = 1$

Вектори називають **колінеарними**, якщо вони розташовані на одній прямій або на паралельних прямих.

![alt text](https://ua.onlinemschool.com/pictures/vector/vector_colinearity.png)


Вектори називають **компланарними**, якщо існує площина, якій вони паралельні.

![alt text](https://ua.onlinemschool.com/pictures/vector/vector_coplanarity.png)

Вектори називають **рівними**, якщо вони колінеарні, однаково спрямовані та мають рівні модулі.

![alt text](https://ua.onlinemschool.com/pictures/vector/vector_equality.png)


Вектори називають **протилежними**, якщо вони колінеарні, протилежно спрямовані та мають рівні модулі.

![alt text](https://resources.cdn.miyklas.com.ua/5c154d84-97c8-4072-9f11-b22aae278674/v_protiv.wmv.png)

In [44]:
import numpy as np
print('Нуль вектор:\n', np.zeros(5))
print('-'*50)
print('Вектор із одиниць:\n', np.ones(5))
print('-'*50)

v1 = np.array([1, 2, 3])
print('Протележний вектор:\n', v1 * -1 )
print('-'*50)
print('Норма вектора:\n', np.linalg.norm(v1))
print('-'*50)

v2 = np.array([4,5,6])
print('Перевірка на рівність:\n', np.array_equal(v1, v2))
print('-'*50)
print('Перевірка на колінеарність:\n', np.all(np.cross(v1, v2) == 0))
print('-'*50)

a = np.array([7, 8, 9])
matrix = np.vstack((v1, v2, a))
det = np.linalg.det(matrix)
# Якщо ці три вектори (v1, v2, a) компланарні, то вони є лінійно залежними, тобто, можна побудувати лінійну комбінацію цих векторів, що дорівнює нулю.
print('Перевірка на компланарність:\n', det == 0)
print('-'*50)

Нуль вектор:
 [0. 0. 0. 0. 0.]
--------------------------------------------------
Вектор із одиниць:
 [1. 1. 1. 1. 1.]
--------------------------------------------------
Протележний вектор:
 [-1 -2 -3]
--------------------------------------------------
Норма вектора:
 3.7416573867739413
--------------------------------------------------
Перевірка на рівність:
 False
--------------------------------------------------
Перевірка на колінеарність:
 False
--------------------------------------------------
Перевірка на компланарність:
 True
--------------------------------------------------


### Як додати 1 до всіх елементів списка?

In [46]:
import numpy as np
a = list(range(5))
a_array = np.array(a)
n = 1
print(f'Python realisation: {[i+n for i in a]}')
print('-'*50)
# За допомогою numpy
print(f'NumPy realisation: {a_array+n}')
print('-'*50)

Python realisation: [1, 2, 3, 4, 5]
--------------------------------------------------
NumPy realisation: [1 2 3 4 5]
--------------------------------------------------


## Дії над векторами

Існують різні операції, які можна виконати з векторами. Ось основні:

- Додавання скаляра до вектора

$\vec v + 1 = (x_v+1, y_v+1)$
- Віднімання скаляра від вектора

$\vec v - 2 = (x_v-2, y_v-2)$
- Множення вектора на скаляр

$\vec v * 2 = (x_v*5, y_v*5)$
- Додавання векторів

$\vec v + \vec w = (x_v+x_w, y_v+y_w)$
- Віднімання векторів

$\vec v - \vec w = (x_v-x_w, y_v-y_w)$
- Скалярний добуток

$(\vec v \cdot \vec w) = (x_v*x_w + y_v*y_w)$

$(\vec v \cdot \vec w) = |\vec v| \cdot |\vec w|*cos(ϕ)$

In [47]:
import numpy as np
a = np.array([1, 2, 3, 4, 5], dtype=float)

# Вектор-скаляр дії
print('Додавання вектора та скаляра:\n', a + 2)  # [3. 4. 5. 6. 7.]
print('-'*50)
print('Віднімання вектора та скаляра:\n', a - 1)  # [0. 1. 2. 3. 4.]
print('-'*50)
print('Множення вектора на скаляр:\n', a * 5 ) # [ 5. 10. 15. 20. 25.]
print('-' * 50)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Вектор-вектор дії
print('Додавання двох векторів:\n', a + b)  # [5 7 9]
print('-'*50)
print('Віднімання двох векторів:\n', a - b)  # [-3 -3 -3]
print('-'*50)
print('Скалярний добуток:\n', np.dot(a, b))  # 32
print('-'*50)

# numpy only
print('По елементне множення (numpy only):\n', a * b)  # [ 4 10 18]
print('-'*50)
print('По елементне ділення (numpy only):\n', b / a)  # [4.  2.5 2. ]
print('-'*50)

Додавання вектора та скаляра:
 [3. 4. 5. 6. 7.]
--------------------------------------------------
Віднімання вектора та скаляра:
 [0. 1. 2. 3. 4.]
--------------------------------------------------
Множення вектора на скаляр:
 [ 5. 10. 15. 20. 25.]
--------------------------------------------------
Додавання двох векторів:
 [5 7 9]
--------------------------------------------------
Віднімання двох векторів:
 [-3 -3 -3]
--------------------------------------------------
Скалярний добуток:
 32
--------------------------------------------------
По елементне множення (numpy only):
 [ 4 10 18]
--------------------------------------------------
По елементне ділення (numpy only):
 [4.  2.5 2. ]
--------------------------------------------------


Скалярний добуток має такі властивості:
1.	$(v,w)=(w,v)$
2.	$v^2=∣v∣^2$
3.	$(λv,w)=λ(v,w)$
4.	$(v+w,u)=(v,u)+(w,u)$

## Базис векторів

У лінійній алгебрі **базис векторів** — це набір векторів, що використовуються для опису інших векторів у лінійному просторі. Кожен вектор в просторі можна представити унікальною лінійною комбінацією базисних векторів з деякими коефіцієнтами.

Це набір векторів, які сприймаються як "основа" або "фундамент" простору. Кожний вектор у просторі може бути представлений у вигляді лінійної комбінації базисних векторів. Основна властивість базису полягає в тому, що будь-який вектор у просторі може бути однозначно виражений у вигляді лінійної комбінації цих базисних векторів.

Наприклад, у двовимірному просторі кожен базис може складатися з двох лінійно незалежних векторів, наприклад, векторів (1, 0) і (0, 1) які спрямовані вздовж координатних вісей x і y відповідно. Цей базис використовується для опису будь-якого вектора у площині за допомогою його координат.


![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/3D_Vector.svg/220px-3D_Vector.svg.png)

## Матриці

**Матриця** - це організована таблиця чисел, яка складається з рядків та стовпців. Кожен елемент матриці зазвичай ідентифікується за допомогою двох індексів: номера рядка та номера стовпця.

Матрицею розмірності *m×n* називатиметься сукупність чисел, які будуть розміщені у таблиці з m рядочків та n стовпчиків

Числа $a_{ij}$ називаються елементами матриці. Таким чином, перший індекс $i$ елементу відповідає за номер рядка, у якому розміщений даний елемент, а другий індекс $j$ — номер стовця. І як ви могли вже здогадатись, така матриця буде належати лінійному простору $R^{m×n}$.

![alt text](https://chem.libretexts.org/@api/deki/files/282975/definition.jpg)

### Операції над матрицями

1. **Сумою матриць** $A = (a_{ij}), B = (b_{ij})$ однакової розмірності $m*n$ називається нова матриця $C = A+B$ тої ж розмірності, елементи якої рівні $c_{ij} = a_{ij} + b_{ij}$.

- Властивість 1. $A + B = B + A$
- Властивість 2. $(A + B)+C = A+(B+C)$
- Властивість 3. $A+ 0 = A$
- Властивість 4. $A + (-A) = 0$

2. **Добутком матриці на число** називається нова матриця $С = α \cdot A$ де $c_{ij} = α \cdot a_{ij}$.

- Властивість 5. $(α \cdot β)A = α ⋅(βA)$
- Властивість 6. $α⋅(A+B) = αA+αB$
- Властивість 7. $A⋅(α+β) = Aα+Aβ$
- Властивість 8. $0⋅A = 0, 1⋅A=A$

3. **Транспонуванням** квадратної матриці називається таке перетворення, при якому її рядки стають стовпцями з тими ж номерами, а стовпці — рядками. Матрицю, транспоновану відносно матриці $A$, позначають $A^T$:

$$A =
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
$$, то
$$A^T =
\begin{pmatrix}
a_{11} & a_{21} & a_{31} \\
a_{12} & a_{22} & a_{32} \\
a_{13} & a_{23} & a_{33}
\end{pmatrix}
$$

![alt text](https://img.madskillsvocabulary.com/img/matemtica/154/Matriz-Transposta_3.jpg)

4. **Множення матриць** — це алгебраїчна операція, яка використовується для обчислення нової матриці шляхом множення двох вихідних матриць. Якщо ми маємо дві матриці A та B, де A має розмірність m×n (тобто має m рядків і n стовпців), а B має розмірність n×p (має n рядків і p стовпців), то їх добуток AB буде матрицею C розмірності m×p, де кожен елемент нової матриці $c_{ij}$ обчислюється як скалярний добуток i-ого рядка матриці A, тобто $\vec{a_i}$, та j-ого стовпця матриці B — $\vec{b_j}$.
![alt text](https://textbook.edu.goit.global/python/data-science-remaster/v1/img/module-01/mul.drawio.svg)

- Властивість 9. $A \cdot B ≠ B\cdot A$
- Властивість 10. $(A×B)×C=A×(B×C)$
- Властивість 11.$(A+B)×C=A×C+B×C$
- Властивість 12.$A×(B+C)=A×B+A×C$
- Властивість 13.$A×E=E×A=A$
- Властивість 14.$A×∅=∅×A=∅$
- Властивість 15.$(A×B)^T = B^T×A^T$


In [49]:
print(1*1+2*0+3*-1)
print(1*2+2*4+3*0)

-2
10


### Види матриць

- Якщо $m=n$, тобто число рядків матриці дорівнює числу стовпців, то матриця називається **квадратною матрицею** порядку $n$.

- Квадратна матриця, у якої всі елементи, що стоять вище та нижче головної діагоналі, дорівнюють нулю, називається діагональною, тобто $a_{ii}≠0, a_{ij}=0$ при $i!=j$. Діагональна матриця третього порядку:

$$M =
\begin{pmatrix}
a_{11} & 0 & 0 \\
0 & a_{22} & 0 \\
0 & 0 & a_{33}
\end{pmatrix}
$$


Діагональ квадратної матриці, складена з елементів $a_{11}, a_{22}, a_{33}, ..., a_{nn}$, називається **головною діагоналлю**.

**Побічною діагоналлю квадратної матриці** називається діагональ, що йде з правого верхнього кута цієї матриці в лівий нижній кут (дзеркально до головної).

- Квадратна матриця називається **одиничною**, якщо на головній діагоналі в неї стоять одиниці, а решта елементів – нулі. Одиничну матрицю прийнято позначати буквою $I$.

$$I =
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$$

- Квадратна матриця, у якої всі елементи, що стоять нижче (або вище) головної діагоналі, дорівнюють нулю, називається **трикутною**, наприклад, трикутна матриця третього порядку:
$$M =
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
0 & a_{22} & a_{23} \\
0 & 0 & a_{33}
\end{pmatrix}
$$

- Матриця ∅ називається нульовою, якщо всі її елементи дорівнюють нулю.
$$0 =
\begin{pmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{pmatrix}
$$

- Обернена матриця $A^{-1}$ це така матриця при множенні її на оригінальну $A$, дає одиничну $I$.

$$A⋅A^{-1}=A^{-1}⋅A = I$$



### Реалізація в numpy

In [50]:
# Слайсування/ Індексація
import numpy as np
a = np.array([
    [1, 2, 3],
     [4, 5, 6],
      [7, 8, 9]])
print('П\'ятий елемент матриці 3х3:\n', a[1, 1])
print('-'*50)
print('Всі елементи з 2 рядка та у 2 стовпчику матриці 3х3:\n', a[1:, 1])
print('-'*50)
print('Всі елементи у 1 рядку до 3 колонки матриці 3х3:\n', a[0, :2])
print('-'*50)

П'ятий елемент матриці 3х3:
 5
--------------------------------------------------
Всі елементи з 2 рядка та у 2 стовпчику матриці 3х3:
 [5 8]
--------------------------------------------------
Всі елементи у 1 рядку до 3 колонки матриці 3х3:
 [1 2]
--------------------------------------------------


In [56]:
# Дії над матрицями

import numpy as np

a = np.array([[1, 2, 3],
              [0, 1, 2]])

b = np.array([[ 1, 2],
              [ 0, 4],
              [-1, 0]])

print('Розмірність першої матриці:\n', a.shape, '\nРозмірність другої матриці:\n', b.shape)
print('-'*50)
print('Множення матриць:\n', np.dot(a, b))
print('-'*50)
print('Транспонування матриць:\n',a.T)
print('-'*50)
print('Зміна розмірності:\n',a.reshape((3, 2)))
print('-'*50)
print('Плоска матриця:\n',a.flatten())
print('-'*50)
print('Одинична матриця:\n', np.eye(4, k=0, dtype=float))
print('-'*50)
a1=np.array([[1, 2],
              [3, 4]])
print('Обернена матриця:\n',np.linalg.inv(a1))
print('-'*50)

Розмірність першої матриці:
 (2, 3) 
Розмірність другої матриці:
 (3, 2)
--------------------------------------------------
Множення матриць:
 [[-2 10]
 [-2  4]]
--------------------------------------------------
Транспонування матриць:
 [[1 0]
 [2 1]
 [3 2]]
--------------------------------------------------
Зміна розмірності:
 [[1 2]
 [3 0]
 [1 2]]
--------------------------------------------------
Плоска матриця:
 [1 2 3 0 1 2]
--------------------------------------------------
Одинична матриця:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------------------------------------
Обернена матриця:
 [[-2.   1. ]
 [ 1.5 -0.5]]
--------------------------------------------------


# Додаткові можливості numpy

In [57]:
# Для створення масиву, що містить послідовність чисел, існують два методи: np.arange та np.linspace
#Метод np.arange аналогічний методу Python range
import numpy as np

a = np.arange(5)
b = np.arange(1, 3, 0.5)
print('Послідовність від 0 до 5:\n',a)
print('-'*50)
print('Послідовність від 1 до 3 з кроком 0.5:\n',b)
print('-'*50)

a = np.linspace(1, 5, num=2)
b = np.linspace(1, 3, num=3)
print('Із послідовності [1-5] виділити 2 елементи на максимальній дистанції один від одного:\n', a)
print('-'*50)
print('Із послідовності [1-3] виділити 3 елементи на максимальній дистанції один від одного:\n', b)
print('-'*50)

Послідовність від 0 до 5:
 [0 1 2 3 4]
--------------------------------------------------
Послідовність від 1 до 3 з кроком 0.5:
 [1.  1.5 2.  2.5]
--------------------------------------------------
Із послідовності [1-5] виділити 2 елементи на максимальній дистанції один від одного:
 [1. 5.]
--------------------------------------------------
Із послідовності [1-3] виділити 3 елементи на максимальній дистанції один від одного:
 [1. 2. 3.]
--------------------------------------------------


In [58]:
# Статистичні функції
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print('Мінімальна величина послідовності [1, 2, 3, 4, 5]:\n',a.min())
print('-'*50)
print('Максимальна величина послідовності [1, 2, 3, 4, 5]:\n',a.max())
print('-'*50)
print('Сума всіх величин послідовності [1, 2, 3, 4, 5]:\n',a.sum())
print('-'*50)
print('Середня величина послідовності [1, 2, 3, 4, 5]:\n',a.mean())
print('-'*50)
print('Множення всіх величин послідовності (факторіал) [1, 2, 3, 4, 5]:\n', a.prod())
print('-'*50)

Мінімальна величина послідовності [1, 2, 3, 4, 5]:
 1
--------------------------------------------------
Максимальна величина послідовності [1, 2, 3, 4, 5]:
 5
--------------------------------------------------
Сума всіх величин послідовності [1, 2, 3, 4, 5]:
 15
--------------------------------------------------
Середня величина послідовності [1, 2, 3, 4, 5]:
 3.0
--------------------------------------------------
Множення всіх величин послідовності (факторіал) [1, 2, 3, 4, 5]:
 120
--------------------------------------------------


In [60]:
# З'єднання матриць
# https://numpy.org/doc/stable/reference/generated/numpy.hstack.html
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.vstack((a, b))
print('Вертикальне з\'єднання (по колонкам):\n', c)
# [[1 2]
#  [3 4]
#  [5 6]]

d = np.hstack((a, b))
print('Горизонтальне з\'єднання (по рядкам):\n', d)
# [[1 2 5 6]
#  [3 4 7 8]]

# А також схожа логіка у dstack, column_stack, stack, concatenate, etc.

Вертикальне з'єднання (по колонкам):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтальне з'єднання (по рядкам):
 [[1 2 5 6]
 [3 4 7 8]]


Що ще?
1. Визначник матриці. Правило трикутника

- https://uk.wikipedia.org/wiki/Визначник
- https://www.mathros.net.ua/obchyslennja-vyznachnykiv-vysokyh-porjadkiv-za-shemoju-rozkladu-vyznachnyka-po-rjadku-chy-stovpci.html
- https://ua.onlinemschool.com/math/assistance/matrix/determinant/

2. Система лінійних aлгебраїчних рівнянь (СЛАР) (Метод Гауса, Метод Крамера)

- https://uk.wikipedia.org/wiki/Система_лінійних_алгебраїчних_рівнянь
- https://uk.wikipedia.org/wiki/Метод_Гауса
- https://uk.wikipedia.org/wiki/Метод_Крамера
- https://www.mathros.net.ua/rozvjazok-systemy-linijnyh-algebraichnyh-rivnjan-metodom-kramera.html