# Module 1 homework

In [24]:
import numpy as np

## 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [25]:
# variant 1
natural_numbers_list = np.array(range(1, 11), dtype=int)
print("одновимірний масив (вектор) з першими 10-ма натуральними числами:\n", natural_numbers_list)

одновимірний масив (вектор) з першими 10-ма натуральними числами:
 [ 1  2  3  4  5  6  7  8  9 10]


In [26]:
# variant 2
natural_numbers_list = np.arange(1, 11)
print("одновимірний масив (вектор) з першими 10-ма натуральними числами:\n", natural_numbers_list)

одновимірний масив (вектор) з першими 10-ма натуральними числами:
 [ 1  2  3  4  5  6  7  8  9 10]


## 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [27]:
# variant 1
two_dimension_array = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
two_dimension_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
# variant 2
matrix_3 = np.zeros((3, 3), dtype=int)
print("Матриця розміром 3x3, заповнена нулями:\n", matrix_3)

Матриця розміром 3x3, заповнена нулями:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


## 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [29]:
random_matrix_int_5 = np.random.randint(1, 11, (5, 5))
print("Матриця розміром 5x5, заповнена випадковими цілими числами в діапазоні від 1 до 10:\n", random_matrix_int_5)


Матриця розміром 5x5, заповнена випадковими цілими числами в діапазоні від 1 до 10:
 [[ 3  5  1  1  5]
 [ 7  5  7  2  1]
 [ 6  2  3  6  5]
 [ 1  4  8  9  4]
 [ 6  7  6 10  5]]


## 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [30]:
random_matrix_4 = np.random.rand(4, 4)
print("Матриця розміром 4x4, заповнена випадковими дійсними числами в діапазоні від 0 до 1:")
print(random_matrix_4)

Матриця розміром 4x4, заповнена випадковими дійсними числами в діапазоні від 0 до 1:
[[0.37707654 0.74771953 0.26298599 0.81313327]
 [0.49750191 0.51856266 0.4712323  0.78369771]
 [0.38330159 0.95011908 0.38919885 0.67023952]
 [0.24013442 0.64879821 0.15772766 0.68280711]]


## 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [31]:
first_arr_5 = np.random.randint(1, 11, 5)
second_arr_5 = np.random.randint(1, 11, 5)

arrays_sum = first_arr_5 + second_arr_5
arrays_substr = first_arr_5 - second_arr_5
arrays_mutl = first_arr_5 * second_arr_5

print("Перший масив:", first_arr_5)
print("Другий масив:", second_arr_5)
print("Сума:", arrays_sum)
print("Різниця:", arrays_substr)
print("Добуток:", arrays_mutl)

Перший масив: [6 8 3 2 7]
Другий масив: [10  4  8  3  8]
Сума: [16 12 11  5 15]
Різниця: [-4  4 -5 -1 -1]
Добуток: [60 32 24  6 56]


## 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [32]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

scalar_dot = np.dot(vector1, vector2)
vector_mult = vector1 * vector2

print("Вектор 1:\n", vector1)
print("Вектор 2:\n", vector2)
print("Добуток векторів:\n", vector_mult)
print("Скалярний добуток:\n", scalar_dot)


Вектор 1:
 [0.20228842 0.86744585 0.39142297 0.97192699 0.67965531 0.55664683
 0.2386193 ]
Вектор 2:
 [0.53433455 0.77991592 0.52189386 0.57184541 0.75238551 0.18236229
 0.74146612]
Добуток векторів:
 [0.10808969 0.67653483 0.20428125 0.55579199 0.51136281 0.10151139
 0.17692813]
Скалярний добуток:
 2.3345000811102437


## 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [33]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 3))

matrix_dot = np.dot(matrix_1, matrix_2)

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Добуток матриць:\n", matrix_dot)

Перша матриця:
 [[7 7]
 [2 2]]
Друга матриця:
 [[ 4  8 10]
 [ 9  1  2]]
Добуток матриць:
 [[91 63 84]
 [26 18 24]]


## 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [34]:
matrix = np.random.randint(1, 11, (3, 3))
# matrix = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]])  # не має оберненої

try:
    inverse_matrix = np.linalg.inv(matrix)
except np.linalg.LinAlgError:
    print("Матриця\n", matrix, "\nне має оберненої")
else:
    print("Матриця:\n", matrix)
    print("Обернена матриця:\n", inverse_matrix)


Матриця:
 [[3 7 2]
 [1 2 5]
 [7 1 4]]
Обернена матриця:
 [[ 0.015 -0.13   0.155]
 [ 0.155 -0.01  -0.065]
 [-0.065  0.23  -0.005]]


## 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [35]:
matrix = np.random.rand(4, 4)
matrix_T = matrix.T
print("Матриця:\n", matrix)
print("Обернена матриця:\n", matrix_T)

Матриця:
 [[0.51859457 0.02028391 0.57152792 0.68825158]
 [0.13313839 0.44895422 0.10806108 0.50304907]
 [0.63223389 0.4825109  0.71353706 0.11527513]
 [0.18119045 0.99101944 0.75228572 0.376658  ]]
Обернена матриця:
 [[0.51859457 0.13313839 0.63223389 0.18119045]
 [0.02028391 0.44895422 0.4825109  0.99101944]
 [0.57152792 0.10806108 0.71353706 0.75228572]
 [0.68825158 0.50304907 0.11527513 0.376658  ]]


## 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [36]:
matrix = np.random.randint(1, 11, (3, 4))
vektor = np.random.randint(1, 11, 4)
result = matrix * vektor

print("Матриця:\n", matrix)
print("Вектор:\n", vektor)
print("Добуток:\n", result)


Матриця:
 [[10  6  3 10]
 [ 1  4  2  6]
 [ 2  5  5  5]]
Вектор:
 [10  8  2  9]
Добуток:
 [[100  48   6  90]
 [ 10  32   4  54]
 [ 20  40  10  45]]


## 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [37]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
result = matrix * vector

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Добуток:\n", result)

Матриця:
 [[0.73015701 0.89289589 0.38783842]
 [0.16056204 0.77443539 0.40494636]]
Вектор:
 [0.9256982  0.93224954 0.52640657]
Добуток:
 [[0.67590503 0.83240178 0.20416069]
 [0.14863199 0.72196704 0.21316642]]


## 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [38]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))

result = matrix_1 * matrix_2

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Поелементне множення матриць:\n", result)

Перша матриця:
 [[6 4]
 [3 9]]
Друга матриця:
 [[ 4  7]
 [ 9 10]]
Поелементне множення матриць:
 [[24 28]
 [27 90]]


## 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [39]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))

result = np.dot(matrix_1, matrix_2)

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Добуток матриць:\n", result)

Перша матриця:
 [[7 4]
 [1 1]]
Друга матриця:
 [[ 5  2]
 [10  2]]
Добуток матриць:
 [[75 22]
 [15  4]]


## 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [40]:
matrix = np.random.randint(1, 101, (5, 5))

result = matrix.sum()

print("Матриця:\n", matrix)
print("Сума елементів матриці:", result)

Матриця:
 [[86 63 84 95 97]
 [32 10 49 80 89]
 [98 19 48 50 20]
 [82 94 46 43 23]
 [99 93  7 68 25]]
Сума елементів матриці: 1500


## 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [41]:
matrix_1 = np.random.randint(1, 11, (4, 4))
matrix_2 = np.random.randint(1, 11, (4, 4))

result = np.subtract(matrix_1, matrix_2)
result2 = matrix_1 - matrix_2

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Різниця матриць:\n", result)
print("Різниця матриць (варіант 2):\n", result2)


Перша матриця:
 [[ 3 10 10  2]
 [ 5  1  5  9]
 [ 6 10  9  1]
 [ 7  1  5 10]]
Друга матриця:
 [[10  7  3  7]
 [ 7  5  3  8]
 [10  7  2  7]
 [ 3  3  2  6]]
Різниця матриць:
 [[-7  3  7 -5]
 [-2 -4  2  1]
 [-4  3  7 -6]
 [ 4 -2  3  4]]
Різниця матриць (варіант 2):
 [[-7  3  7 -5]
 [-2 -4  2  1]
 [-4  3  7 -6]
 [ 4 -2  3  4]]


## 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [42]:
matrix = np.random.rand(3, 3)

sum_vector = np.sum(matrix, axis=1)
sum_vector_col = sum_vector.reshape((-1, 1))
sum_vector2 = np.reshape(np.array([matrix[0].sum(), matrix[1].sum(), matrix[2].sum()]), (3, 1))

print("Матриця:\n", matrix)
print("Вектор-стовпчик:\n", sum_vector_col)
print("Вектор-стовпчик (варіант 2):\n", sum_vector2)

Матриця:
 [[0.30726409 0.08570105 0.04814289]
 [0.25069241 0.74485447 0.61283005]
 [0.3987995  0.42513871 0.20387572]]
Вектор-стовпчик:
 [[0.44110803]
 [1.60837693]
 [1.02781393]]
Вектор-стовпчик (варіант 2):
 [[0.44110803]
 [1.60837693]
 [1.02781393]]


## 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [43]:
matrix = np.random.randint(1, 11, (3, 4))

result = np.square(matrix)

print("Матриця:\n", matrix)
print("Матриця з квадратами чисел:\n", result)

Матриця:
 [[ 5  9  9 10]
 [ 2  7  3  5]
 [ 7  4  3  6]]
Матриця з квадратами чисел:
 [[ 25  81  81 100]
 [  4  49   9  25]
 [ 49  16   9  36]]


## 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [44]:
vector = np.random.randint(1, 51, 4)
result = np.sqrt(vector)
print("Вектор:\n", vector)
print("Вектор з квадратними коренями:\n", result)

Вектор:
 [ 9 47 37 46]
Вектор з квадратними коренями:
 [3.         6.8556546  6.08276253 6.78232998]
