# Module 1 homework

In [1]:
import numpy as np

## 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
# variant 1
natural_numbers_list = np.array(range(1, 11), dtype=int)
print("одновимірний масив (вектор) з першими 10-ма натуральними числами:")
natural_numbers_list

одновимірний масив (вектор) з першими 10-ма натуральними числами:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# variant 2
natural_numbers_list = np.arange(1, 11)
print("одновимірний масив (вектор) з першими 10-ма натуральними числами:")
natural_numbers_list

одновимірний масив (вектор) з першими 10-ма натуральними числами:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
# variant 1
two_dimension_array = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
two_dimension_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
# variant 2
matrix_3 = np.zeros((3, 3), dtype=int)
print("Матриця розміром 3x3, заповнена нулями:\n", matrix_3)

Матриця розміром 3x3, заповнена нулями:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


## 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [6]:
random_matrix_int_5 = np.random.randint(1, 11, (5, 5))
print("Матриця розміром 5x5, заповнена випадковими цілими числами в діапазоні від 1 до 10:")
random_matrix_int_5

Матриця розміром 5x5, заповнена випадковими цілими числами в діапазоні від 1 до 10:


array([[ 8,  2,  3, 10,  1],
       [ 9,  2,  1,  9, 10],
       [ 9,  1,  8,  3,  8],
       [ 9,  6,  2, 10,  4],
       [ 5,  2,  5,  1, 10]])

## 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [7]:
random_matrix_4 = np.random.rand(4, 4)
print("Матриця розміром 4x4, заповнена випадковими дійсними числами в діапазоні від 0 до 1:")
print(random_matrix_4)

Матриця розміром 4x4, заповнена випадковими дійсними числами в діапазоні від 0 до 1:
[[0.66412461 0.82404256 0.28558328 0.64630581]
 [0.13063167 0.1906694  0.32940777 0.21237753]
 [0.06860583 0.25824475 0.05894663 0.62838253]
 [0.60047537 0.09399463 0.0889237  0.21190901]]


## 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [8]:
first_arr_5 = np.random.randint(1, 11, 5)
second_arr_5 = np.random.randint(1, 11, 5)

arrays_sum = first_arr_5 + second_arr_5
arrays_substr = first_arr_5 - second_arr_5
arrays_mutl = first_arr_5 * second_arr_5

print("Перший масив:", first_arr_5)
print("Другий масив:", second_arr_5)
print("Сума:", arrays_sum)
print("Різниця:", arrays_substr)
print("Добуток:", arrays_mutl)

Перший масив: [7 1 1 3 2]
Другий масив: [ 3  5 10  1  6]
Сума: [10  6 11  4  8]
Різниця: [ 4 -4 -9  2 -4]
Добуток: [21  5 10  3 12]


## 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [9]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

scalar_dot = np.dot(vector1, vector2)
print("Вектор 1:\n", vector1)
print("Вектор 2:\n", vector2)
print("Скалярний добуток:\n", scalar_dot)


Вектор 1:
 [0.74006984 0.04080106 0.46848807 0.97280016 0.73956808 0.70199574
 0.3832327 ]
Вектор 2:
 [0.38774206 0.96877759 0.19552432 0.35395461 0.07658459 0.13199887
 0.32914801]
Скалярний добуток:
 1.0378537094279316


## 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [10]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 3))

matrix_dot = np.dot(matrix_1, matrix_2)

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Добуток матриць:\n", matrix_dot)

Перша матриця:
 [[ 6  8]
 [ 1 10]]
Друга матриця:
 [[8 9 6]
 [4 2 5]]
Добуток матриць:
 [[80 70 76]
 [48 29 56]]


## 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [11]:
matrix = np.random.randint(1, 11, (3, 3))
# matrix = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]])  # не має оберненої

try:
    inverse_matrix = np.linalg.inv(matrix)
except np.linalg.LinAlgError:
    print("Матриця\n", matrix, "\nне має оберненої")
else:
    print("Матриця:\n", matrix)
    print("Обернена матриця:\n", inverse_matrix)


Матриця:
 [[ 8  8 10]
 [ 2  5  5]
 [ 6  3  4]]
Обернена матриця:
 [[-0.20833333  0.08333333  0.41666667]
 [-0.91666667  1.16666667  0.83333333]
 [ 1.         -1.         -1.        ]]


## 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [12]:
matrix = np.random.rand(4, 4)
inverse_matrix = np.linalg.inv(matrix)
print("Матриця:\n", matrix)
print("Обернена матриця:\n", inverse_matrix)

Матриця:
 [[0.72826852 0.9540593  0.52700533 0.81528618]
 [0.81640826 0.61655698 0.4247058  0.02191956]
 [0.53807098 0.12604062 0.40760237 0.64922343]
 [0.06420939 0.27801644 0.45012582 0.27028556]]
Обернена матриця:
 [[-0.35590834  0.9897007   1.0093203  -1.43108291]
 [ 1.30395683 -0.07729111 -1.65272017  0.04284677]
 [-1.25154251  0.62613218  0.4198113   2.71597733]
 [ 0.82757969 -1.19835536  0.76107517 -0.52742249]]


## 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [13]:
matrix = np.random.randint(1, 11, (3, 4))
vektor = np.random.randint(1, 11, 4)
result = np.dot(matrix, vektor)

print("Матриця:\n", matrix)
print("Вектор:\n", vektor)
print("Добуток:\n", result)


Матриця:
 [[ 6  5  4  4]
 [ 4  5 10  9]
 [10 10  9  5]]
Вектор:
 [6 1 8 1]
Добуток:
 [ 77 118 147]


## 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [14]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Добуток:\n", result)

Матриця:
 [[0.87874027 0.04421948 0.06367085]
 [0.38863188 0.34714573 0.0563435 ]]
Вектор:
 [0.95037804 0.09232183 0.7178897 ]
Добуток:
 [0.88492653 0.44184475]


## 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [15]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))

result = matrix_1 * matrix_2

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Поелементне множення матриць:\n", result)

Перша матриця:
 [[3 2]
 [3 3]]
Друга матриця:
 [[10  4]
 [ 6  6]]
Поелементне множення матриць:
 [[30  8]
 [18 18]]


## 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [16]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))

result = np.dot(matrix_1, matrix_2)

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Добуток матриць:\n", result)

Перша матриця:
 [[8 2]
 [5 4]]
Друга матриця:
 [[10  6]
 [ 4  3]]
Добуток матриць:
 [[88 54]
 [66 42]]


## 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [17]:
matrix = np.random.randint(1, 101, (5, 5))

result = matrix.sum()

print("Матриця:\n", matrix)
print("Сума елементів матриці:", result)

Матриця:
 [[31 60 94 42 92]
 [88 25 35 78 13]
 [53 87 40 97 50]
 [10 59 39 38 54]
 [64 25 45 84 13]]
Сума елементів матриці: 1316


## 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [18]:
matrix_1 = np.random.randint(1, 11, (4, 4))
matrix_2 = np.random.randint(1, 11, (4, 4))

result = np.subtract(matrix_1, matrix_2)

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Різниця матриць:\n", result)


Перша матриця:
 [[ 5  5  2  7]
 [ 3  9  4  3]
 [ 6  5  8  9]
 [10  7  8  3]]
Друга матриця:
 [[ 4  6 10  3]
 [ 6  8  4  1]
 [ 1  7  5  6]
 [ 5 10  1  5]]
Різниця матриць:
 [[ 1 -1 -8  4]
 [-3  1  0  2]
 [ 5 -2  3  3]
 [ 5 -3  7 -2]]


## 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [19]:
matrix = np.random.rand(3, 3)

sum_vector = np.sum(matrix, axis=1)

print("Матриця:\n", matrix)
print("Вектор-стовпчик:\n", sum_vector)

Матриця:
 [[0.96296175 0.87650827 0.94305901]
 [0.6160101  0.99317394 0.66986187]
 [0.80998718 0.23401391 0.1642974 ]]
Вектор-стовпчик:
 [2.78252903 2.27904592 1.20829849]


## 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [20]:
matrix = np.random.randint(1, 11, (3, 4))

result = np.square(matrix)

print("Матриця:\n", matrix)
print("Матриця з квадратами чисел:\n", result)

Матриця:
 [[1 7 4 4]
 [6 9 5 9]
 [8 4 1 6]]
Матриця з квадратами чисел:
 [[ 1 49 16 16]
 [36 81 25 81]
 [64 16  1 36]]


## 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [21]:
vector = np.random.randint(1, 51, 4)
result = np.sqrt(vector)
print("Вектор:\n", vector)
print("Вектор з квадратними коренями:\n", result)

Вектор:
 [15 31 38 38]
Вектор з квадратними коренями:
 [3.87298335 5.56776436 6.164414   6.164414  ]
