# Module 1 homework

In [22]:
import numpy as np

## 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [23]:
# variant 1
natural_numbers_list = np.array(range(1, 11), dtype=int)
print("одновимірний масив (вектор) з першими 10-ма натуральними числами:\n", natural_numbers_list)

одновимірний масив (вектор) з першими 10-ма натуральними числами:
 [ 1  2  3  4  5  6  7  8  9 10]


In [24]:
# variant 2
natural_numbers_list = np.arange(1, 11)
print("одновимірний масив (вектор) з першими 10-ма натуральними числами:\n", natural_numbers_list)

одновимірний масив (вектор) з першими 10-ма натуральними числами:
 [ 1  2  3  4  5  6  7  8  9 10]


## 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [25]:
# variant 1
two_dimension_array = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
two_dimension_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
# variant 2
matrix_3 = np.zeros((3, 3), dtype=int)
print("Матриця розміром 3x3, заповнена нулями:\n", matrix_3)

Матриця розміром 3x3, заповнена нулями:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


## 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [27]:
random_matrix_int_5 = np.random.randint(1, 11, (5, 5))
print("Матриця розміром 5x5, заповнена випадковими цілими числами в діапазоні від 1 до 10:\n", random_matrix_int_5)


Матриця розміром 5x5, заповнена випадковими цілими числами в діапазоні від 1 до 10:
 [[ 5  3  1  8  8]
 [ 4  5  5  5  6]
 [10  1  5  4  7]
 [10  9 10  5  6]
 [ 7  8 10  9  9]]


## 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [28]:
random_matrix_4 = np.random.rand(4, 4)
print("Матриця розміром 4x4, заповнена випадковими дійсними числами в діапазоні від 0 до 1:")
print(random_matrix_4)

Матриця розміром 4x4, заповнена випадковими дійсними числами в діапазоні від 0 до 1:
[[0.17110402 0.12967461 0.95176222 0.78543358]
 [0.2570409  0.92422592 0.20675815 0.75424816]
 [0.95795699 0.71837336 0.63661125 0.80745163]
 [0.53148403 0.70668798 0.54460407 0.60510715]]


## 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [29]:
first_arr_5 = np.random.randint(1, 11, 5)
second_arr_5 = np.random.randint(1, 11, 5)

arrays_sum = first_arr_5 + second_arr_5
arrays_substr = first_arr_5 - second_arr_5
arrays_mutl = first_arr_5 * second_arr_5

print("Перший масив:", first_arr_5)
print("Другий масив:", second_arr_5)
print("Сума:", arrays_sum)
print("Різниця:", arrays_substr)
print("Добуток:", arrays_mutl)

Перший масив: [3 1 5 4 2]
Другий масив: [ 1 10  2  4  6]
Сума: [ 4 11  7  8  8]
Різниця: [ 2 -9  3  0 -4]
Добуток: [ 3 10 10 16 12]


## 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [30]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

scalar_dot = np.dot(vector1, vector2)
vector_mult = vector1 * vector2

print("Вектор 1:\n", vector1)
print("Вектор 2:\n", vector2)
print("Добуток векторів:\n", vector_mult)
print("Скалярний добуток:\n", scalar_dot)


Вектор 1:
 [0.25664356 0.96818401 0.65036615 0.22710387 0.65378324 0.57299987
 0.84848361]
Вектор 2:
 [0.89675962 0.69545611 0.54315836 0.09610604 0.25499903 0.29473375
 0.97246123]
Добуток векторів:
 [0.23014759 0.67332949 0.35325181 0.02182605 0.16671409 0.1688824
 0.82511742]
Скалярний добуток:
 2.439268849742297


## 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [31]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 3))

matrix_dot = np.dot(matrix_1, matrix_2)

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Добуток матриць:\n", matrix_dot)

Перша матриця:
 [[ 5  7]
 [10  9]]
Друга матриця:
 [[ 1  5  9]
 [10  4  5]]
Добуток матриць:
 [[ 75  53  80]
 [100  86 135]]


## 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [32]:
matrix = np.random.randint(1, 11, (3, 3))
# matrix = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]])  # не має оберненої

try:
    inverse_matrix = np.linalg.inv(matrix)
except np.linalg.LinAlgError:
    print("Матриця\n", matrix, "\nне має оберненої")
else:
    print("Матриця:\n", matrix)
    print("Обернена матриця:\n", inverse_matrix)


Матриця:
 [[ 1  2  9]
 [ 5 10  3]
 [ 8  1  7]]
Обернена матриця:
 [[-1.06349206e-01  7.93650794e-03  1.33333333e-01]
 [ 1.74603175e-02  1.03174603e-01 -6.66666667e-02]
 [ 1.19047619e-01 -2.38095238e-02  8.26058798e-19]]


## 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [33]:
matrix = np.random.rand(4, 4)
matrix_T = matrix.T
print("Матриця:\n", matrix)
print("Обернена матриця:\n", matrix_T)

Матриця:
 [[0.18981965 0.98868416 0.84643065 0.40564057]
 [0.43934195 0.11173959 0.69618677 0.39153742]
 [0.4008809  0.66707962 0.92036578 0.60957023]
 [0.65176162 0.84032086 0.71066203 0.06765947]]
Обернена матриця:
 [[0.18981965 0.43934195 0.4008809  0.65176162]
 [0.98868416 0.11173959 0.66707962 0.84032086]
 [0.84643065 0.69618677 0.92036578 0.71066203]
 [0.40564057 0.39153742 0.60957023 0.06765947]]


## 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [34]:
matrix = np.random.randint(1, 11, (3, 4))
vektor = np.random.randint(1, 11, 4)
result = matrix * vektor

print("Матриця:\n", matrix)
print("Вектор:\n", vektor)
print("Добуток:\n", result)


Матриця:
 [[ 1  9  3  4]
 [ 8  4  7  4]
 [10  9  4  3]]
Вектор:
 [4 2 8 6]
Добуток:
 [[ 4 18 24 24]
 [32  8 56 24]
 [40 18 32 18]]


## 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [35]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
result = matrix * vector

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Добуток:\n", result)

Матриця:
 [[0.24089822 0.65497569 0.15465379]
 [0.28442505 0.27825525 0.02876144]]
Вектор:
 [0.89107732 0.58093812 0.36714457]
Добуток:
 [[0.21465894 0.38050035 0.0567803 ]
 [0.25344471 0.16164908 0.01055961]]


## 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [36]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))

result = matrix_1 * matrix_2

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Поелементне множення матриць:\n", result)

Перша матриця:
 [[ 5 10]
 [10  8]]
Друга матриця:
 [[9 9]
 [8 5]]
Поелементне множення матриць:
 [[45 90]
 [80 40]]


## 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [37]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))

result = np.dot(matrix_1, matrix_2)

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Добуток матриць:\n", result)

Перша матриця:
 [[3 5]
 [9 8]]
Друга матриця:
 [[10  2]
 [ 2  5]]
Добуток матриць:
 [[ 40  31]
 [106  58]]


## 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [38]:
matrix = np.random.randint(1, 101, (5, 5))

result = matrix.sum()

print("Матриця:\n", matrix)
print("Сума елементів матриці:", result)

Матриця:
 [[48 85  8 43 63]
 [36 10 63 83 52]
 [94 46 99 77  6]
 [36 93 28 20 10]
 [80  6 85 63 23]]
Сума елементів матриці: 1257


## 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [39]:
matrix_1 = np.random.randint(1, 11, (4, 4))
matrix_2 = np.random.randint(1, 11, (4, 4))

result = np.subtract(matrix_1, matrix_2)
result2 = matrix_1 - matrix_2

print("Перша матриця:\n", matrix_1)
print("Друга матриця:\n", matrix_2)
print("Різниця матриць:\n", result)
print("Різниця матриць (варіант 2):\n", result2)


Перша матриця:
 [[ 7  7  4  8]
 [10  1  1  4]
 [ 6  6  4  1]
 [ 5  3  2  8]]
Друга матриця:
 [[ 7  6  4  2]
 [ 4 10 10  9]
 [ 9 10  6  5]
 [ 9  2  9  7]]
Різниця матриць:
 [[ 0  1  0  6]
 [ 6 -9 -9 -5]
 [-3 -4 -2 -4]
 [-4  1 -7  1]]
Різниця матриць (варіант 2):
 [[ 0  1  0  6]
 [ 6 -9 -9 -5]
 [-3 -4 -2 -4]
 [-4  1 -7  1]]


## 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [40]:
matrix = np.random.rand(3, 3)

sum_vector = np.sum(matrix, axis=1)
sum_vector2 = np.array([matrix[0].sum(), matrix[1].sum(), matrix[2].sum()])

print("Матриця:\n", matrix)
print("Вектор-стовпчик:\n", sum_vector)
print("Вектор-стовпчик (варіант 2):\n", sum_vector2)

Матриця:
 [[0.01330532 0.11011603 0.73427921]
 [0.62720856 0.84550558 0.8413868 ]
 [0.95218843 0.78957243 0.95552942]]
Вектор-стовпчик:
 [0.85770055 2.31410094 2.69729028]
Вектор-стовпчик (варіант 2):
 [0.85770055 2.31410094 2.69729028]


## 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [41]:
matrix = np.random.randint(1, 11, (3, 4))

result = np.square(matrix)

print("Матриця:\n", matrix)
print("Матриця з квадратами чисел:\n", result)

Матриця:
 [[9 3 1 6]
 [7 4 3 7]
 [7 7 6 7]]
Матриця з квадратами чисел:
 [[81  9  1 36]
 [49 16  9 49]
 [49 49 36 49]]


## 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [42]:
vector = np.random.randint(1, 51, 4)
result = np.sqrt(vector)
print("Вектор:\n", vector)
print("Вектор з квадратними коренями:\n", result)

Вектор:
 [27 39 40 25]
Вектор з квадратними коренями:
 [5.19615242 6.244998   6.32455532 5.        ]
